-- Global permission catalog. Tenant roles are created by the tenant bootstrap service.

INSERT INTO permissions (code, resource, action, description)
VALUES
    ('dashboard.read', 'dashboard', 'read', 'View tenant dashboard metrics'),
    ('user.read', 'user', 'read', 'View tenant users'),
    ('user.invite', 'user', 'invite', 'Invite tenant users'),
    ('user.manage', 'user', 'manage', 'Manage tenant users'),
    ('role.read', 'role', 'read', 'View roles and permission catalog'),
    ('role.manage', 'role', 'manage', 'Manage tenant roles'),
    ('customer.read_own', 'customer', 'read_own', 'Read assigned customers'),
    ('customer.read_team', 'customer', 'read_team', 'Read team customers'),
    ('customer.read_all', 'customer', 'read_all', 'Read all tenant customers'),
    ('customer.create', 'customer', 'create', 'Create customers'),
    ('customer.update_own', 'customer', 'update_own', 'Update assigned customers'),
    ('customer.update_all', 'customer', 'update_all', 'Update all tenant customers'),
    ('customer.assign', 'customer', 'assign', 'Assign customer ownership'),
    ('customer.delete', 'customer', 'delete', 'Delete or anonymize customers'),
    ('customer.score', 'customer', 'score', 'Recalculate customer intent'),
    ('customer.score_read', 'customer', 'score_read', 'View customer scoring results'),
    ('conversation.read_own', 'conversation', 'read_own', 'Read assigned conversations'),
    ('conversation.read_team', 'conversation', 'read_team', 'Read team conversations'),
    ('conversation.read_all', 'conversation', 'read_all', 'Read all tenant conversations'),
    ('conversation.assign', 'conversation', 'assign', 'Assign conversations'),
    ('conversation.takeover', 'conversation', 'takeover', 'Take over AI conversations'),
    ('conversation.ai_manage', 'conversation', 'ai_manage', 'Enable or suspend AI replies'),
    ('conversation.close', 'conversation', 'close', 'Close conversations'),
    ('message.send', 'message', 'send', 'Send customer messages'),
    ('ai_run.read', 'ai_run', 'read', 'View AI run audit data'),
    ('ai_run.feedback', 'ai_run', 'feedback', 'Submit AI quality feedback'),
    ('ai_agent.preview', 'ai_agent', 'preview', 'Preview AI responses'),
    ('ai_agent.evaluate', 'ai_agent', 'evaluate', 'Run AI evaluation suites'),
    ('ai_agent.chat', 'ai_agent', 'chat', 'Run AI chat for a customer conversation'),
    ('prompt.read', 'prompt', 'read', 'View prompt versions'),
    ('prompt.create', 'prompt', 'create', 'Create prompt drafts'),
    ('prompt.update', 'prompt', 'update', 'Update prompt drafts'),
    ('prompt.publish', 'prompt', 'publish', 'Publish or retire prompts'),
    ('knowledge.read', 'knowledge', 'read', 'View knowledge collections and files'),
    ('knowledge.upload', 'knowledge', 'upload', 'Upload knowledge files'),
    ('knowledge.manage', 'knowledge', 'manage', 'Manage and synchronize knowledge'),
    ('knowledge.delete', 'knowledge', 'delete', 'Delete knowledge resources'),
    ('knowledge.test', 'knowledge', 'test', 'Test knowledge retrieval'),
    ('product.read', 'product', 'read', 'View products'),
    ('product.create', 'product', 'create', 'Create products'),
    ('product.update', 'product', 'update', 'Update products'),
    ('quotation.read_own', 'quotation', 'read_own', 'Read own quotations'),
    ('quotation.read_all', 'quotation', 'read_all', 'Read all tenant quotations'),
    ('quotation.create', 'quotation', 'create', 'Create quotations'),
    ('quotation.update_own', 'quotation', 'update_own', 'Update own draft quotations'),
    ('quotation.ai_assist', 'quotation', 'ai_assist', 'Use AI quotation assistance'),
    ('quotation.submit', 'quotation', 'submit', 'Submit quotations for approval'),
    ('quotation.approve', 'quotation', 'approve', 'Approve or reject quotations'),
    ('quotation.send', 'quotation', 'send', 'Send approved quotations'),
    ('quotation.cancel', 'quotation', 'cancel', 'Cancel quotations'),
    ('connector.read', 'connector', 'read', 'View connector metadata'),
    ('connector.manage', 'connector', 'manage', 'Manage connectors'),
    ('connector.secret_manage', 'connector', 'secret_manage', 'Manage connector secrets'),
    ('connector.log_read', 'connector', 'log_read', 'View redacted webhook logs'),
    ('connector.replay', 'connector', 'replay', 'Replay webhook events'),
    ('workflow.read', 'workflow', 'read', 'View workflows'),
    ('workflow.manage', 'workflow', 'manage', 'Manage workflow drafts'),
    ('workflow.publish', 'workflow', 'publish', 'Publish and activate workflows'),
    ('workflow.test', 'workflow', 'test', 'Test workflows'),
    ('workflow.run_read', 'workflow', 'run_read', 'View workflow runs'),
    ('notification.retry', 'notification', 'retry', 'Retry failed notifications'),
    ('notification.send', 'notification', 'send', 'Create outbound notifications'),
    ('system_config.read', 'system_config', 'read', 'View tenant configuration'),
    ('system_config.manage', 'system_config', 'manage', 'Manage tenant configuration'),
    ('audit.read', 'audit', 'read', 'Read tenant audit logs'),
    ('data.export', 'data', 'export', 'Export tenant data')
AS new
ON DUPLICATE KEY UPDATE
    resource = new.resource,
    action = new.action,
    description = new.description,
    updated_at = CURRENT_TIMESTAMP(6);
